### ISSUE TITLE
Bad permissions: systemd-tmpfiles

### ISSUE THREAD

**Issue by d10n** [thelounge/thelounge-archlinux#17] opened 2020-04-24 17:12 UTC
When trying to perform a fresh install of thelounge, the install does not complete:
```
:: Running post-transaction hooks...
(1/4) Creating system user accounts...
(2/4) Reloading system manager configuration...
(3/4) Creating temporary files...
error: command failed to execute correctly
(4/4) Arming ConditionNeedsUpdate...
```
`thelounge:thelounge` owns `/etc/thelounge`, but
`root:root` owns `/etc/thelounge/config.js`, which systemd-tmpfiles does not like:
```
$ sudo /usr/bin/systemd-tmpfiles --create
Detected unsafe path transition /etc/thelounge -> /etc/thelounge/config.js during canonicalization of /etc/thelounge/config.js.
```

The problem was fixed in https://github.com/thelounge/thelounge-archlinux/pull/16 but that PR was not merged, so I am creating this issue to track it independently of the PR.

**Comment by brunnre8** [comment] 2020-04-24 21:23
It was fixed on the master branch.
I can't reproduce your issue, works fine for me on a fresh Arch installation

**Closed as completed by brunnre8** 2020-04-24 21:23 UTC

**Comment by brunnre8** [comment] 2020-04-24 21:31
```
sudo pacman -Syu thelounge
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 custom is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) thelounge-4.1.0-2

Total Installed Size:  33.04 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                            [##############################] 100%
(1/1) checking package integrity                          [##############################] 100%
(1/1) loading package files                               [##############################] 100%
(1/1) checking for file conflicts                         [##############################] 100%
(1/1) checking available disk space                       [##############################] 100%
:: Processing package changes...
(1/1) installing thelounge                                [##############################] 100%
:: Running post-transaction hooks...
(1/4) Creating system user accounts...
(2/4) Reloading system manager configuration...
(3/4) Creating temporary files...
(4/4) Arming ConditionNeedsUpdate...
```

```
>sudo systemd-tmpfiles --create
>echo $?
0
```

And that on a box which has never seen the package before

**Comment by d10n** [comment] 2020-04-25 03:48
Ah, I didn't notice the update to the master branch. I will test installation later this week and report back. Thanks
